apiVersion: v1
kind: Service
metadata:
  name: ats-matcher-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
      name: ui
    - port: 8000
      targetPort: 8000
      name: api
  selector:
    app: ats-matcher
